"""arq worker for long-running Media-Service jobs.

Currently handles one job type: transcription. The worker process uses the
configured hosted STT provider and runs jobs from Redis until shut down.

Run via: `arq src.worker.WorkerSettings`
Or via:  `make worker`
"""

from __future__ import annotations

import asyncio
from datetime import datetime, timezone
import hashlib
import json
import os
import pickle
import tempfile
import time
from typing import Any
from urllib.parse import urlsplit, urlunsplit
from uuid import uuid4

import httpx

from arq import Retry
from arq.jobs import deserialize_job_raw
from arq.worker import func

from redis.asyncio import Redis

from src.clients.cms import CMSClient
from src.clients.safe_fetch import SafeFetchClient
from src.config import Settings
from src.middleware.request_id import _request_id_ctx
from src.models.manager import ModelManager
from src.queue import build_redis_settings
from src.services.transcription import TranscriptionService, provider_error_code
from src.services.segmented_audio import extract_audio_segment
from src.services.workload import WorkloadAdmission
from src.utils.logging import get_logger, setup_logging
from src.utils.metrics import transcribe_jobs_total
from src.utils.tempdir import resolve_media_temp_dir

logger = get_logger("media-worker")

# ARQ cron jobs are persisted in the same sorted set as real work.  A long
# transcription therefore used to put every ten-second dispatcher tick ahead
# of the next media job.  Dispatchers now run as bounded background loops (see
# ``_start_dispatchers``) and the worker only accepts real effect jobs from
# ARQ.  These constants are also used to remove the old, safe-to-discard cron
# deliveries left by pre-repair workers.
_ARQ_QUEUE_KEY = "arq:queue"
_ARQ_JOB_PREFIX = "arq:job:"
_ARQ_RETRY_PREFIX = "arq:retry:"
_ARQ_IN_PROGRESS_PREFIX = "arq:in-progress:"
# arq 0.26+ names a unique cron delivery as
# ``<function_name>:<scheduled_epoch_ms>`` (there is no ``cron:`` namespace).
# Keep the older prefixed spellings as compatibility aliases because a few
# development workers used that convention before the queue repair landed.
_CRON_JOB_PREFIXES = (
    "artifact_coverage_dispatch_tick:",
    "content_stage_dispatch_tick:",
    "transcription_segment_dispatch_tick:",
    "cron:artifact_coverage_dispatch_tick:",
    "cron:content_stage_dispatch_tick:",
    "cron:transcription_segment_dispatch_tick:",
)
_STALE_CRON_REAPER_LIMIT = 5_000
_ORPHAN_DELIVERY_REAPER_LIMIT = 512
_EXPIRED_CLAIM_REAPER_LIMIT = 512
_DELIVERY_REAPER_INTERVAL_SECONDS = 30.0
# A queued claim is not useful if it will expire before ARQ can start it. Keep
# a small hand-off margin so the CMS recovery worker, rather than a stale ARQ
# delivery, owns the retry when the queue is under pressure.
_EXPIRED_CLAIM_SAFETY_MS = 15_000
_DISPATCH_LOCK_TTL_SECONDS = 90
# All three dispatch lanes share one ARQ queue and one STT owner.  A
# lane-specific lock lets the lanes observe the same empty queue concurrently
# and enqueue three claims before the depth guard runs again.  The global lock
# below makes claim -> enqueue a single critical section, preserving the
# installation-wide one-effect-at-a-time contract.
_DISPATCH_LOCK_KEY = "wahb:media-dispatch"
# ``arq:queue`` retains active jobs until they finish, so this bound covers
# both active and waiting deliveries.  Media has one STT owner and the Pods
# pipeline is intentionally sequential; accepting more than one ARQ effect
# only creates a waiting tail whose CMS claims can expire before execution.
_MAX_ARQ_JOBS = 1
_MAX_ARQ_QUEUE_DEPTH = _MAX_ARQ_JOBS


def _redis_url_without_database(url: str) -> str:
    """Return a Redis DSN whose database is selected by ARQ_REDIS_DB.

    ``redis-py`` gives a URL path precedence over the ``db=`` keyword.  The
    local env intentionally contains a path for another service, which meant
    the migration-quiesce connection silently used the wrong Redis database.
    Keep unix-socket URLs untouched and strip only the numeric DB path from
    TCP Redis URLs.
    """

    parsed = urlsplit(url)
    if parsed.scheme not in {"redis", "rediss"}:
        return url
    if not parsed.path or parsed.path == "/":
        return url
    return urlunsplit((parsed.scheme, parsed.netloc, "", parsed.query, parsed.fragment))


async def _prune_stale_cron_deliveries(redis: Any) -> int:
    """Delete only obsolete ARQ cron deliveries from the shared queue.

    These records contain no user payload and are regenerated by the bounded
    dispatch loops.  Real jobs, future cron records, and jobs currently being
    executed are intentionally left alone.  This is a targeted migration of
    the old scheduler backlog, never a Redis flush.
    """

    try:
        # Once this worker starts, the in-process loops are the sole scheduler
        # authority.  Remove both overdue and not-yet-due records emitted by a
        # previous ARQ-cron worker; retaining a future legacy tick would make
        # ARQ fail it as an unknown function and still pollute the queue.
        ids = await redis.zrange(_ARQ_QUEUE_KEY, start=0, end=_STALE_CRON_REAPER_LIMIT - 1)
    except Exception as exc:
        logger.warning("stale_cron_reaper_unavailable", error=str(exc))
        return 0

    stale_ids: list[str] = []
    for raw_id in ids:
        job_id = raw_id.decode() if isinstance(raw_id, bytes) else str(raw_id)
        if not job_id.startswith(_CRON_JOB_PREFIXES):
            continue
        try:
            if await redis.exists(f"{_ARQ_IN_PROGRESS_PREFIX}{job_id}"):
                continue
        except Exception:
            # If we cannot prove that a delivery is not in progress, preserve
            # it; the next worker restart can retry the safe cleanup.
            continue
        stale_ids.append(job_id)

    if not stale_ids:
        return 0

    # The initial read above is only a candidate scan.  ARQ may pick a job
    # between that read and cleanup, so perform the in-progress check and
    # removal atomically for each id.  In particular, never delete a payload
    # after a worker has installed its in-progress marker.
    remove_script = """
    if redis.call('exists', ARGV[2] .. ARGV[1]) == 0
      and redis.call('zscore', KEYS[1], ARGV[1]) then
      redis.call('zrem', KEYS[1], ARGV[1])
      redis.call('del', ARGV[3] .. ARGV[1], ARGV[4] .. ARGV[1])
      return 1
    end
    return 0
    """
    try:
        async with redis.pipeline(transaction=False) as pipe:
            for job_id in stale_ids:
                pipe.eval(
                    remove_script,
                    1,
                    _ARQ_QUEUE_KEY,
                    job_id,
                    _ARQ_IN_PROGRESS_PREFIX,
                    _ARQ_JOB_PREFIX,
                    _ARQ_RETRY_PREFIX,
                )
            results = await pipe.execute()
    except Exception as exc:
        logger.warning("stale_cron_reaper_failed", error=str(exc), candidates=len(stale_ids))
        return 0

    removed = sum(int(value or 0) for value in results)
    if removed:
        logger.warning("stale_cron_deliveries_pruned", count=removed)
    return removed


async def _prune_orphaned_deliveries(redis: Any) -> int:
    """Remove queue records whose ARQ payload has already disappeared.

    ARQ stores the runnable id in ``arq:queue`` and the serialized payload in
    ``arq:job:<id>``.  A process crash, a Redis eviction, or an interrupted
    mixed-version migration can leave the sorted-set member behind.  ARQ then
    spends a worker slot attempting an expired job, while the dispatch depth
    guard treats the orphan as real capacity.  Only an id for which no job,
    retry, or in-progress marker exists is eligible; durable work is never
    inferred absent from a queue length alone.

    The final removal is an atomic Lua check so a concurrent enqueue of the
    same deterministic id cannot be deleted between the read and zrem.
    """

    try:
        ids = await redis.zrange(
            _ARQ_QUEUE_KEY, start=0, end=_ORPHAN_DELIVERY_REAPER_LIMIT - 1
        )
    except Exception as exc:
        logger.warning("orphan_delivery_reaper_unavailable", error=str(exc))
        return 0

    candidates: list[str] = []
    for raw_id in ids:
        job_id = raw_id.decode() if isinstance(raw_id, bytes) else str(raw_id)
        # Cron records are handled by the dedicated migration helper.  Leaving
        # them here also makes the two reapers safe to run concurrently.
        if job_id.startswith(_CRON_JOB_PREFIXES):
            continue
        try:
            has_job = await redis.exists(f"{_ARQ_JOB_PREFIX}{job_id}")
            has_retry = await redis.exists(f"{_ARQ_RETRY_PREFIX}{job_id}")
            in_progress = await redis.exists(f"{_ARQ_IN_PROGRESS_PREFIX}{job_id}")
        except Exception:
            # If Redis cannot prove that a delivery is orphaned, preserve it;
            # CMS lease recovery remains the authoritative safety net.
            continue
        if not has_job and not has_retry and not in_progress:
            candidates.append(job_id)

    if not candidates:
        return 0

    remove_script = """
    if redis.call('exists', ARGV[2] .. ARGV[1]) == 0
      and redis.call('exists', ARGV[3] .. ARGV[1]) == 0
      and redis.call('exists', ARGV[4] .. ARGV[1]) == 0 then
      return redis.call('zrem', KEYS[1], ARGV[1])
    end
    return 0
    """
    removed = 0
    try:
        async with redis.pipeline(transaction=False) as pipe:
            for job_id in candidates:
                pipe.eval(
                    remove_script,
                    1,
                    _ARQ_QUEUE_KEY,
                    job_id,
                    _ARQ_JOB_PREFIX,
                    _ARQ_RETRY_PREFIX,
                    _ARQ_IN_PROGRESS_PREFIX,
                )
            results = await pipe.execute()
        removed = sum(int(value or 0) for value in results)
    except Exception as exc:
        logger.warning(
            "orphan_delivery_reaper_failed",
            error=str(exc),
            candidates=len(candidates),
        )
        return 0

    if removed:
        logger.warning("orphaned_arq_deliveries_pruned", count=removed)
    return removed


def _lease_expiry_ms(value: Any) -> int | None:
    """Normalize a durable lease timestamp carried by an ARQ payload."""

    if isinstance(value, (int, float)) and not isinstance(value, bool):
        numeric = float(value)
        # Treat seconds and milliseconds defensively; CMS currently emits an
        # RFC3339 string, but old deliveries used epoch seconds in a few jobs.
        if 0 < numeric < 10_000_000_000:
            numeric *= 1000
        return int(numeric) if numeric > 0 else None
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        parsed = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return int(parsed.timestamp() * 1000)


def _claim_expiry_from_delivery(raw_payload: bytes) -> int | None:
    """Extract a CMS claim expiry from a Media-owned ARQ job payload.

    Ordinary URL transcription jobs deliberately return ``None``: they do not
    carry a content-stage lease and must never be deleted by this reaper. A
    malformed or unknown payload also remains untouched so CMS can reconcile it
    through its normal expiry path instead of the worker guessing ownership.
    """

    try:
        function_name, args, _kwargs, _job_try, _enqueue_time = deserialize_job_raw(
            raw_payload, deserializer=pickle.loads
        )
    except Exception:
        return None
    if not args or not isinstance(args[0], dict):
        return None
    claim = args[0]
    value: Any = None
    if function_name == "content_stage_transcript_task":
        value = claim.get("lease_expires_at")
    elif function_name == "artifact_coverage_task":
        value = claim.get("lease_expires_at")
    elif function_name == "transcription_segment_task":
        unit = claim.get("unit")
        if isinstance(unit, dict):
            value = unit.get("lease_expires_at")
    return _lease_expiry_ms(value)


async def _prune_expired_claim_deliveries(redis: Any) -> int:
    """Remove queued Media deliveries that are expired or too close to expiry.

    A dispatcher claims work in CMS before putting the payload in ARQ. If ARQ
    is backed up, that payload can sit past its lease and then consume a worker
    slot only to receive a fenced 409. Remove only recognized Media-owned
    deliveries that are expired or inside the hand-off safety margin and are
    not in progress; the durable CMS request remains the source of truth and
    will be requeued by lease recovery. This is targeted queue hygiene, never a
    Redis flush.
    """

    try:
        ids = await redis.zrange(
            _ARQ_QUEUE_KEY, start=0, end=_EXPIRED_CLAIM_REAPER_LIMIT - 1
        )
    except Exception as exc:
        logger.warning("expired_claim_reaper_unavailable", error=str(exc))
        return 0

    now_ms = int(time.time() * 1000)
    candidates: list[tuple[str, int]] = []
    for raw_id in ids:
        job_id = raw_id.decode() if isinstance(raw_id, bytes) else str(raw_id)
        if job_id.startswith(_CRON_JOB_PREFIXES):
            continue
        try:
            if await redis.exists(f"{_ARQ_IN_PROGRESS_PREFIX}{job_id}"):
                continue
            payload = await redis.get(f"{_ARQ_JOB_PREFIX}{job_id}")
        except Exception:
            # Do not remove anything unless Redis proves both the payload and
            # the absence of an active worker marker.
            continue
        if not isinstance(payload, (bytes, bytearray)):
            continue
        expires_at = _claim_expiry_from_delivery(bytes(payload))
        if expires_at is not None and expires_at <= now_ms + _EXPIRED_CLAIM_SAFETY_MS:
            candidates.append((job_id, expires_at))

    if not candidates:
        return 0

    remove_script = """
    if redis.call('exists', ARGV[2] .. ARGV[1]) == 0
      and redis.call('exists', ARGV[3] .. ARGV[1]) == 1
      and redis.call('zscore', KEYS[1], ARGV[1]) then
      redis.call('zrem', KEYS[1], ARGV[1])
      redis.call('del', ARGV[3] .. ARGV[1], ARGV[4] .. ARGV[1])
      return 1
    end
    return 0
    """
    removed = 0
    try:
        async with redis.pipeline(transaction=False) as pipe:
            for job_id, _expires_at in candidates:
                pipe.eval(
                    remove_script,
                    1,
                    _ARQ_QUEUE_KEY,
                    job_id,
                    _ARQ_IN_PROGRESS_PREFIX,
                    _ARQ_JOB_PREFIX,
                    _ARQ_RETRY_PREFIX,
                )
            results = await pipe.execute()
        removed = sum(int(value or 0) for value in results)
    except Exception as exc:
        logger.warning(
            "expired_claim_reaper_failed",
            error=str(exc),
            candidates=len(candidates),
        )
        return 0

    if removed:
        logger.warning("expired_claim_deliveries_pruned", count=removed)
    return removed


async def _prune_scheduler_deliveries(ctx: dict[str, Any]) -> None:
    """Run queue hygiene at a bounded cadence from the dispatch loops."""

    now = time.monotonic()
    last_run = float(ctx.get("dispatch_reaper_at", 0.0))
    if now - last_run < _DELIVERY_REAPER_INTERVAL_SECONDS:
        return
    # All dispatch loops run on the same event loop. Set the timestamp before
    # the first await so only one loop performs this pass.
    ctx["dispatch_reaper_at"] = now
    redis = ctx["redis"]
    await _prune_stale_cron_deliveries(redis)
    await _prune_expired_claim_deliveries(redis)
    await _prune_orphaned_deliveries(redis)


async def _runnable_queue_depth(redis: Any) -> int:
    """Count only deliveries that are due to run now.

    Delayed retry records are durable backoff, not runnable pressure. Counting
    them in the dispatch guard can freeze all three lanes behind a large set of
    future retries even though ARQ would not execute them yet.
    """

    try:
        now_ms = int(time.time() * 1000)
        return int(await redis.zcount(_ARQ_QUEUE_KEY, "-inf", now_ms) or 0)
    except Exception:
        # Older Redis-compatible test doubles may not implement ZCOUNT. The
        # conservative fallback preserves the original safety bound.
        return int(await redis.zcard(_ARQ_QUEUE_KEY) or 0)


async def _release_dispatch_lock(redis: Any, key: str, token: str) -> None:
    # Compare-and-delete prevents a slow CMS request from deleting a newer
    # worker's lock after the old TTL has elapsed.
    try:
        await redis.eval(
            "if redis.call('get', KEYS[1]) == ARGV[1] then return redis.call('del', KEYS[1]) else return 0 end",
            1,
            key,
            token,
        )
    except Exception as exc:
        logger.warning("media_dispatch_lock_release_failed", key=key, error=str(exc))


async def _run_dispatch_once(
    ctx: dict[str, Any], lane: str, callback: Any
) -> None:
    redis = ctx["redis"]
    # ``lane`` remains in logs and metrics, but the lock is deliberately global
    # because all lanes enqueue into the same ARQ sorted set.
    lock_key = _DISPATCH_LOCK_KEY
    lock_token = uuid4().hex
    try:
        acquired = await redis.set(
            lock_key, lock_token, nx=True, ex=_DISPATCH_LOCK_TTL_SECONDS
        )
    except Exception as exc:
        logger.warning("media_dispatch_lock_unavailable", lane=lane, error=str(exc))
        return
    if not acquired:
        return
    try:
        await _prune_scheduler_deliveries(ctx)
        try:
            depth = await _runnable_queue_depth(redis)
        except Exception as exc:
            # A Redis read failure must not turn into an unbounded CMS claim
            # storm.  Skip this tick and let the next one retry.
            logger.warning("media_dispatch_depth_unavailable", lane=lane, error=str(exc))
            return
        if depth >= _MAX_ARQ_QUEUE_DEPTH:
            last_log = ctx.setdefault("dispatch_backpressure_log", {})
            now = time.monotonic()
            if now - float(last_log.get(lane, 0)) >= 30:
                logger.warning(
                    "media_dispatch_backpressure",
                    lane=lane,
                    queue_depth=depth,
                    limit=_MAX_ARQ_QUEUE_DEPTH,
                )
                last_log[lane] = now
            return
        await callback(ctx)
    finally:
        await _release_dispatch_lock(redis, lock_key, lock_token)


async def _dispatch_loop(
    ctx: dict[str, Any], lane: str, callback: Any, interval_seconds: float
) -> None:
    stop: asyncio.Event = ctx["dispatch_stop"]
    while not stop.is_set():
        started = time.monotonic()
        try:
            await _run_dispatch_once(ctx, lane, callback)
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            # A transient CMS/Redis failure must not terminate the scheduler;
            # durable claim recovery will make the next tick safe.
            logger.warning("media_dispatch_tick_failed", lane=lane, error=str(exc))
        remaining = max(0.25, interval_seconds - (time.monotonic() - started))
        try:
            await asyncio.wait_for(stop.wait(), timeout=remaining)
        except asyncio.TimeoutError:
            pass


async def _fair_dispatch_loop(ctx: dict[str, Any]) -> None:
    # Never make local lanes race for the distributed lock. Rotate the first
    # lane too, so a busy lane cannot monopolize the one-effect queue limit.
    stop = ctx["dispatch_stop"]
    first = 0
    while not stop.is_set():
        specs = _DISPATCH_SPECS[first:] + _DISPATCH_SPECS[:first]
        for lane, callback, _interval in specs:
            if stop.is_set():
                return
            try:
                await _run_dispatch_once(ctx, lane, callback)
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                logger.warning("media_dispatch_tick_failed", lane=lane, error=str(exc))
        first = (first + 1) % len(_DISPATCH_SPECS)
        try:
            await asyncio.wait_for(stop.wait(), timeout=min(s[2] for s in _DISPATCH_SPECS))
        except asyncio.TimeoutError:
            pass


async def _start_dispatchers(ctx: dict[str, Any]) -> None:
    """Start one fair scheduler for all Media-owned lanes."""

    if "redis" not in ctx:
        return
    # Clean the pre-repair queue before the first ARQ poll. Otherwise the
    # worker can spend its initial four slots executing deliveries whose CMS
    # lease is already dead, delaying the first valid claim for another 30s
    # reaper interval.
    await _prune_stale_cron_deliveries(ctx["redis"])
    await _prune_expired_claim_deliveries(ctx["redis"])
    await _prune_orphaned_deliveries(ctx["redis"])
    ctx["dispatch_stop"] = asyncio.Event()
    ctx["dispatch_tasks"] = [
        asyncio.create_task(
            _fair_dispatch_loop(ctx),
            name="media-dispatch",
        )
    ]


async def _stop_dispatchers(ctx: dict[str, Any]) -> None:
    stop = ctx.get("dispatch_stop")
    if stop is not None:
        stop.set()
    tasks = list(ctx.get("dispatch_tasks") or [])
    if tasks:
        await asyncio.gather(*tasks, return_exceptions=True)
    ctx.pop("dispatch_tasks", None)


async def _lease_heartbeat_loop(
    stop: asyncio.Event,
    failed: asyncio.Event,
    callback: Any,
    label: str,
    interval_seconds: float = 15.0,
) -> None:
    """Renew a durable lease without allowing a failed heartbeat task to die.

    The previous implementation let an HTTP exception escape the background
    task.  The effect then continued with no renewal and the exception was
    only observed when ``finally`` awaited the task, often after CMS had
    already fenced the attempt.  Keep the controller alive, record every
    failure, and let the owner return an explicit uncertain receipt.
    """

    while True:
        try:
            await asyncio.wait_for(stop.wait(), timeout=interval_seconds)
            return
        except asyncio.TimeoutError:
            try:
                response = await callback()
                if isinstance(response, dict) and response.get("lease_expires_at"):
                    logger.debug(
                        "media_lease_heartbeat_renewed",
                        owner=label,
                        lease_expires_at=response["lease_expires_at"],
                    )
            except asyncio.CancelledError:
                raise
            except Exception as exc:
                failed.set()
                logger.warning(
                    "media_lease_heartbeat_failed",
                    owner=label,
                    error=str(exc),
                )

async def _startup(ctx: dict[str, Any]) -> None:
    settings = Settings()
    setup_logging(log_level=settings.LOG_LEVEL, json_output=settings.is_production)
    logger.info("worker_starting", env=settings.ENV)

    config_errors, config_warnings = settings.validate_startup(expected_role="worker")
    for warning in config_warnings:
        logger.warning("config_warning", error=warning)
    if config_errors:
        raise RuntimeError("Refusing worker startup: " + "; ".join(config_errors))

    model_manager = ModelManager(settings)
    cms_client = CMSClient(settings)
    fetch_client = SafeFetchClient()
    admission = WorkloadAdmission(stt_limit=1, clip_limit=1)
    temp_dir = resolve_media_temp_dir(settings.MEDIA_TEMP_DIR)

    # The API is the sole CLIP owner. This worker only needs STT and forwards
    # durable image claims to the authenticated API route.
    await model_manager.warmup(["stt"])
    if not model_manager.stt.is_loaded:
        await cms_client.close()
        raise RuntimeError("Refusing worker startup: STT provider is not ready")

    if not await cms_client.health_check():
        await cms_client.close()
        raise RuntimeError("Refusing worker startup: CMS is not reachable")

    # ``REDIS_URL`` may carry another service's database in its path (for
    # example ``redis://localhost:6379/3``).  Strip that path before applying
    # the Media-specific ARQ database so migration-quiesce checks observe the
    # same database as the ARQ pool.
    redis = Redis.from_url(
        _redis_url_without_database(settings.REDIS_URL), db=settings.ARQ_REDIS_DB
    )
    try:
        await redis.ping()
    except Exception as exc:
        await cms_client.close()
        raise RuntimeError("Refusing worker startup: Redis is not reachable") from exc

    ctx["settings"] = settings
    ctx["model_manager"] = model_manager
    ctx["cms_client"] = cms_client
    ctx["temp_dir"] = temp_dir
    ctx["fetch_client"] = fetch_client
    ctx["workload_admission"] = admission
    ctx["migration_redis"] = redis
    await _start_dispatchers(ctx)
    logger.info(
        "worker_ready",
        stt_provider=model_manager.stt.name,
        stt_loaded=model_manager.stt.is_loaded,
    )


async def _embed_via_api(
    ctx: dict[str, Any],
    image_url: str,
    content_id: str,
    *,
    content_stage: dict[str, str] | None = None,
    artifact_recovery: dict[str, str] | None = None,
) -> dict[str, Any]:
    settings: Settings = ctx["settings"]
    token = settings.service_auth_token
    if not token:
        raise RuntimeError("Media API token is unavailable for image embedding")
    async with httpx.AsyncClient(timeout=httpx.Timeout(90, connect=10)) as client:
        response = await client.post(
            f"{settings.MEDIA_API_BASE_URL.rstrip('/')}/v1/embed/image",
            data={
                "url": image_url,
                "content_id": content_id,
                "content_stage_json": json.dumps(content_stage) if content_stage else "",
                "artifact_recovery_json": json.dumps(artifact_recovery) if artifact_recovery else "",
            },
            headers={"Authorization": f"Bearer {token}"},
        )
    response.raise_for_status()
    payload = response.json()
    if not isinstance(payload, dict):
        raise RuntimeError("Media API returned invalid image embedding response")
    return payload


async def _shutdown(ctx: dict[str, Any]) -> None:
    await _stop_dispatchers(ctx)
    cms_client = ctx.get("cms_client")
    fetch_client = ctx.get("fetch_client")
    if cms_client is not None:
        try:
            await cms_client.close()
        except Exception:
            pass
    if fetch_client is not None:
        await fetch_client.aclose()
    model_manager = ctx.get("model_manager")
    if model_manager is not None:
        await model_manager.stt.aclose()
    admission = ctx.get("workload_admission")
    if admission is not None:
        admission.shutdown()
    migration_redis = ctx.get("migration_redis")
    if migration_redis is not None:
        await migration_redis.aclose()
    logger.info("worker_shutdown")


async def transcribe_task(
    ctx: dict[str, Any],
    url: str,
    content_id: str | None,
    transcription_job_id: str | None,
    language: str | None,
    word_timestamps: bool,
    request_id: str | None = None,
    media_size_bytes: int | None = None,
    artifact_recovery: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Run one durable URL transcription task."""
    migration_redis = ctx.get("migration_redis")
    if migration_redis is not None and await migration_redis.exists("wahb:database-migration:media-quiesced"):
        raise Retry(defer=5)
    # Restore the request-id contextvar so structured logs + outbound headers
    # in this worker process carry the same trace id as the enqueueing API call.
    token = _request_id_ctx.set(request_id) if request_id else None
    service: TranscriptionService | None = None
    try:
        model_manager: ModelManager = ctx["model_manager"]
        cms_client: CMSClient = ctx["cms_client"]
        service = TranscriptionService(
            model_manager.stt,
            cms_client,
            temp_dir=ctx.get("temp_dir"),
            fetch_client=ctx.get("fetch_client"),
            max_download_bytes=ctx["settings"].MAX_UPLOAD_MB * 1024 * 1024
            if "settings" in ctx
            else 200 * 1024 * 1024,
            admission=ctx.get("workload_admission"),
        )

        if not model_manager.stt.is_loaded:
            if transcription_job_id:
                await service._update_job(
                    transcription_job_id,
                    {
                        "status": "failed",
                        "provider": model_manager.stt.name,
                        "model": model_manager.stt.model_size,
                        "error_message": "STT engine is not ready in worker",
                        "provider_error_code": "stt_not_ready",
                    },
                )
            transcribe_jobs_total.labels(state="failed").inc()
            raise RuntimeError("STT engine is not ready in worker")

        logger.info(
            "transcribe_task_started",
            job_id=ctx.get("job_id"),
            content_id=content_id,
            has_url=True,
        )

        response = await service.transcribe_url(
            url,
            content_id=content_id,
            transcription_job_id=transcription_job_id,
            language=language,
            media_size_bytes=media_size_bytes,
            word_timestamps=word_timestamps,
            artifact_recovery=artifact_recovery,
        )

        transcribe_jobs_total.labels(state="completed").inc()
        logger.info(
            "transcribe_task_completed",
            job_id=ctx.get("job_id"),
            content_id=content_id,
            write_back_status=response.write_back_status,
        )
        return response.model_dump()
    except Exception as exc:
        if transcription_job_id and service is not None:
            await service._update_job(
                transcription_job_id,
                {
                    "status": "failed",
                    "error_message": str(exc),
                    "provider_error_code": provider_error_code(exc),
                    "metadata": {
                        "media_size_bytes": media_size_bytes,
                    }
                    if media_size_bytes is not None
                    else None,
                },
            )
        transcribe_jobs_total.labels(state="failed").inc()
        logger.error(
            "transcribe_task_failed",
            job_id=ctx.get("job_id"),
            content_id=content_id,
            error=str(exc),
        )
        raise
    finally:
        if token is not None:
            _request_id_ctx.reset(token)


def _delivery_job_id(claim: dict[str, Any], prefix: str | None = None) -> str:
    """Build a queue id that changes when CMS reclaims a lease.

    CMS deliberately keeps the durable attempt id stable across a safe
    pre-effect reclaim.  ARQ, however, treats a stable ``_job_id`` as an
    already-delivered job for up to 24 hours.  Including the claim token lets
    a fresh delivery coexist with (and safely fence) an old queued payload.
    """

    base = str(prefix or claim.get("deterministic_job_id") or "media-delivery")
    token = str(
        claim.get("claim_token")
        or (claim.get("unit") or {}).get("claim_token")
        or claim.get("attempt_id")
        or uuid4().hex
    )
    suffix = hashlib.sha256(token.encode("utf-8")).hexdigest()[:24]
    return f"{base}:delivery:{suffix}"


async def _defer_content_stage_delivery(
    ctx: dict[str, Any], claim: dict[str, Any], reason: str
) -> None:
    try:
        await ctx["cms_client"].content_stage_transition(
            claim,
            "deferred",
            retry_after_sec=30,
            summary=reason,
        )
    except Exception as exc:
        logger.warning(
            "content_stage_delivery_defer_failed",
            request_id=claim.get("request_id"),
            error=str(exc),
        )


async def artifact_coverage_dispatch_tick(ctx: dict[str, Any]) -> None:
    claim = await ctx["cms_client"].claim_artifact_coverage()
    if not claim:
        return
    try:
        await ctx["redis"].enqueue_job(
            "artifact_coverage_task",
            claim,
            _job_id=_delivery_job_id(claim),
        )
    except Exception as exc:
        logger.warning(
            "artifact_coverage_delivery_failed",
            request_id=claim.get("id"),
            error=str(exc),
        )
        try:
            await ctx["cms_client"].mark_artifact_coverage_uncertain(
                claim["id"], claim["claim_token"]
            )
        except Exception as receipt_exc:
            logger.warning(
                "artifact_coverage_delivery_receipt_failed",
                request_id=claim.get("id"),
                error=str(receipt_exc),
            )


async def content_stage_dispatch_tick(ctx: dict[str, Any]) -> None:
    claim = await ctx["cms_client"].claim_content_stage()
    if not claim:
        return
    try:
        await ctx["redis"].enqueue_job(
            "content_stage_transcript_task",
            claim,
            _job_id=_delivery_job_id(claim),
        )
    except Exception as exc:
        logger.warning(
            "content_stage_delivery_failed",
            request_id=claim.get("request_id"),
            error=str(exc),
        )
        await _defer_content_stage_delivery(
            ctx, claim, "ARQ delivery failed; retrying after scheduler backoff"
        )
        return
    try:
        await ctx["cms_client"].content_stage_transition(claim, "accepted")
    except Exception as exc:
        # The ARQ payload is already durable.  Let the task attempt its fenced
        # begin; if this acceptance receipt was lost, CMS lease recovery will
        # reconcile it instead of creating a second effect.
        logger.warning(
            "content_stage_delivery_acceptance_failed",
            request_id=claim.get("request_id"),
            error=str(exc),
        )


async def content_stage_transcript_task(
    ctx: dict[str, Any], claim: dict[str, Any]
) -> dict[str, str]:
    cms: CMSClient = ctx["cms_client"]
    if claim.get("stage") not in {"pods_transcript", "pods_image_embedding"}:
        await cms.content_stage_transition(
            claim,
            "failed",
            failure_class="unsupported_media_stage",
            summary="Media worker only accepts pods_transcript",
        )
        return {"request_id": claim["request_id"], "state": "failed"}
    try:
        await cms.content_stage_transition(claim, "begin")
    except httpx.HTTPStatusError as exc:
        # A queued payload may legitimately outlive a CMS lease reclaim.  It
        # has no authority to mutate anything, so consume it quietly; the
        # scheduler will deliver a fresh claim with a new token.
        if exc.response.status_code in {404, 409}:
            logger.info(
                "content_stage_delivery_stale",
                request_id=claim.get("request_id"),
                claim_token=claim.get("claim_token"),
            )
            return {"request_id": claim["request_id"], "state": "stale"}
        raise
    stop = asyncio.Event()
    heartbeat_failed = asyncio.Event()
    heartbeat_task = asyncio.create_task(
        _lease_heartbeat_loop(
            stop,
            heartbeat_failed,
            lambda: cms.content_stage_transition(claim, "heartbeat"),
            f"content-stage:{claim['request_id']}",
        )
    )

    async def effect_state(state: str) -> dict[str, str]:
        if heartbeat_failed.is_set() and state == "verifying":
            try:
                await cms.content_stage_transition(
                    claim,
                    "uncertain",
                    summary="Lease heartbeat failed while media effect was running",
                )
            except Exception as exc:
                logger.warning(
                    "content_stage_heartbeat_uncertainty_receipt_failed",
                    request_id=claim.get("request_id"),
                    error=str(exc),
                )
            return {"request_id": claim["request_id"], "state": "uncertain"}
        return {"request_id": claim["request_id"], "state": state}

    try:
        content = claim["bounded_input"]
        if claim["stage"] == "pods_image_embedding":
            image_url = content.get("thumbnail_url")
            if not image_url:
                await cms.content_stage_transition(
                    claim,
                    "failed",
                    failure_class="invalid_input",
                    summary="Image embedding stage has no CMS-approved thumbnail URL",
                )
                return {"request_id": claim["request_id"], "state": "failed"}
            response = await _embed_via_api(
                ctx, image_url, claim["content_item_id"],
                content_stage=cms.content_stage_correlation(claim),
            )
            if response.get("write_back_status") != "ok":
                await cms.content_stage_transition(
                    claim, "uncertain", summary="Image embedding writeback outcome is unknown"
                )
                return {"request_id": claim["request_id"], "state": "uncertain"}
            return await effect_state("verifying")
        caption = content.get("caption_artifact")
        if isinstance(caption, dict):
            full_text = caption.get("full_text")
            raw_segments = caption.get("segments", [])
            segments = raw_segments if isinstance(raw_segments, list) else None
            if (
                isinstance(full_text, str)
                and full_text.strip()
                and len(full_text) <= 2_000_000
                and segments is not None
                and len(segments) <= 10_000
            ):
                chapters = caption.get("chapters")
                await cms.create_transcript(
                    content_item_id=claim["content_item_id"],
                    full_text=full_text,
                    language=str(caption.get("language") or "und"),
                    segments=segments,
                    chapters=chapters if isinstance(chapters, list) else None,
                    source=str(caption.get("source") or "youtube_auto"),
                    provider=str(caption.get("provider") or "youtube"),
                    transcription_job_id=content.get("transcription_job_id"),
                    content_stage=cms.content_stage_correlation(claim),
                )
                return await effect_state("verifying")
            # Empty/partial discovery placeholders are not captions.  The CMS
            # admission guard excludes them from new claims; an old queued
            # claim may still carry one, so drop it and continue through the
            # normal generated-STT policy instead of failing forever without a
            # provider transcript.
            logger.warning(
                "provider_caption_artifact_unusable",
                content_item_id=claim.get("content_item_id"),
            )
        long_form_generation = await ensure_long_form_transcription_generation(ctx, claim, content)
        if long_form_generation is not None:
            return await effect_state("verifying")
        url = content.get("analysis_audio_url") or content.get("playback_url") or content.get("media_url")
        if not url:
            await cms.content_stage_transition(
                claim,
                "failed",
                failure_class="invalid_input",
                summary="Transcript stage has no CMS-approved media URL",
            )
            return {"request_id": claim["request_id"], "state": "failed"}
        service = TranscriptionService(
            ctx["model_manager"].stt,
            cms,
            temp_dir=ctx.get("temp_dir"),
            fetch_client=ctx.get("fetch_client"),
            admission=ctx.get("workload_admission"),
        )
        response = await service.transcribe_url(
            url,
            content_id=claim["content_item_id"],
            transcription_job_id=content.get("transcription_job_id"),
            word_timestamps=True,
            content_stage=cms.content_stage_correlation(claim),
        )
        if response.write_back_status != "ok":
            await cms.content_stage_transition(
                claim, "uncertain", summary="Transcript writeback outcome is unknown"
            )
            return {"request_id": claim["request_id"], "state": "uncertain"}
        return await effect_state("verifying")
    except Exception:
        try:
            await cms.content_stage_transition(
                claim, "uncertain", summary="Transcript effect may have started"
            )
        except Exception:
            pass
        raise
    finally:
        stop.set()
        await asyncio.gather(heartbeat_task, return_exceptions=True)


def _digest(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


async def ensure_long_form_transcription_generation(
    ctx: dict[str, Any], claim: dict[str, Any], content: dict[str, Any]
) -> dict[str, Any] | None:
    duration_raw = content.get("duration_sec")
    try:
        duration_sec = float(duration_raw or 0)
    except (TypeError, ValueError):
        duration_sec = 0
    if duration_sec <= 2400:
        return None
    url = content.get("playback_url") or content.get("media_url")
    if not isinstance(url, str) or not url.strip():
        raise RuntimeError("long-form transcript stage has no CMS-approved playback URL")

    settings: Settings = ctx["settings"]
    cms: CMSClient = ctx["cms_client"]
    content_id = str(claim["content_item_id"])
    tenant_id = str(claim.get("tenant_id") or "default")
    provider = ctx["model_manager"].stt.name
    model = ctx["model_manager"].stt.model_size
    language = str(content.get("content_language") or settings.STT_DEFAULT_LANGUAGE)
    input_digest = _digest(f"long-form-analysis-audio:v1|{url}|{duration_sec:.3f}|{language}|{provider}|{model}")
    existing_manifest_id = content.get("analysis_audio_manifest_id")
    if not isinstance(existing_manifest_id, str) or not existing_manifest_id.strip():
        # A repaired/legacy parent may reuse its source manifest only when the
        # CMS already proves it is audio. Never invent a verified manifest for
        # an arbitrary public URL; Aggregation must first materialize and
        # verify analysis audio for a video source.
        existing_manifest_id = content.get("media_artifact_manifest_id")
        if not isinstance(existing_manifest_id, str) or not existing_manifest_id.strip():
            raise RuntimeError("long-form transcription requires a manifest-owned analysis-audio artifact")
    manifest = await cms.get_artifact_manifest(existing_manifest_id, tenant_id)
    manifest_content_type = str(manifest.get("content_type") or "").lower()
    if not manifest_content_type.startswith("audio/"):
        raise RuntimeError("long-form transcription source manifest is not audio")
    if str(manifest.get("state") or "") not in {"verified", "active"}:
        raise RuntimeError("long-form transcription source manifest is not verified")
    url = str(manifest.get("public_url") or content.get("analysis_audio_url") or url)
    if not url.strip():
        raise RuntimeError("long-form transcription manifest has no public URL")
    input_digest = _digest(f"long-form-analysis-audio:v1|{url}|{duration_sec:.3f}|{language}|{provider}|{model}")

    segment_length_ms = 15 * 60 * 1000
    overlap_ms = 5_000
    total_ms = max(1, int(duration_sec * 1000))
    segments: list[dict[str, Any]] = []
    index = 0
    target_start = 0
    while target_start < total_ms:
        target_end = min(total_ms, target_start + segment_length_ms)
        start_ms = max(0, target_start - (overlap_ms if target_start else 0))
        segment_digest = _digest(f"{input_digest}|{index}|{start_ms}|{target_end}|{overlap_ms}")
        segments.append({
            "start_ms": start_ms,
            "end_ms": target_end,
            "overlap_ms": target_start - start_ms,
            "source_digest": input_digest,
            "segment_digest": segment_digest,
            "artifact_manifest_id": manifest["id"],
        })
        index += 1
        target_start = target_end
    return await cms.create_transcription_generation({
        "tenant_id": tenant_id,
        "content_item_id": content_id,
        "transcription_job_id": content.get("transcription_job_id") or claim["request_id"],
        "input_digest": input_digest,
        "analysis_audio_manifest_id": manifest["id"],
        "provider": provider,
        "model": model,
        "language": language,
        "content_stage": cms.content_stage_correlation(claim),
        "segments": segments,
    })


async def transcription_segment_dispatch_tick(ctx: dict[str, Any]) -> None:
    claim = await ctx["cms_client"].claim_transcription_segment()
    if not claim:
        return
    unit = claim.get("unit") or {}
    unit_id = str(unit.get("id") or "")
    attempt = str(unit.get("attempt_count") or "0")
    if not unit_id:
        return
    try:
        await ctx["redis"].enqueue_job(
            "transcription_segment_task",
            claim,
            _job_id=_delivery_job_id(
                claim,
                prefix=f"transcription-segment-{unit_id}-{attempt}",
            ),
        )
    except Exception as exc:
        # The claim remains fenced and will be recovered by CMS when its lease
        # expires.  Do not let a temporary Redis error terminate the scheduler.
        logger.warning(
            "transcription_segment_delivery_failed",
            segment_id=unit_id,
            error=str(exc),
        )


_DISPATCH_SPECS = (
    ("artifact_coverage", artifact_coverage_dispatch_tick, 10.0),
    ("content_stage", content_stage_dispatch_tick, 10.0),
    ("transcription_segment", transcription_segment_dispatch_tick, 10.0),
)


async def transcription_segment_task(ctx: dict[str, Any], claim: dict[str, Any]) -> dict[str, str]:
    cms: CMSClient = ctx["cms_client"]
    unit = claim.get("unit") or {}
    generation = claim.get("generation") or {}
    unit_id = str(unit["id"])
    claim_token = unit.get("claim_token")
    unit_fence = unit.get("unit_fence_token") or unit.get("fence_token")
    if not isinstance(claim_token, str) or not claim_token.strip() or not isinstance(unit_fence, str) or not unit_fence.strip() or not unit.get("lease_expires_at"):
        raise RuntimeError("transcription segment claim is missing execution credentials")
    # The claim endpoint intentionally leaves the effect boundary untouched.
    # Mark it running before ffmpeg/STT so an expired lease is reconciled as
    # effect-started work rather than being blindly reclaimed while a segment
    # is still being processed.
    try:
        await cms.transition_transcription_segment(
            unit_id,
            "running",
            {
                "claim_token": claim_token,
                "summary": "transcription segment effect started",
            },
        )
    except httpx.HTTPStatusError as exc:
        if exc.response.status_code in {404, 409}:
            logger.info("transcription_segment_delivery_stale", segment_id=unit_id)
            return {"segment_id": unit_id, "state": "stale"}
        raise
    manifest_id = unit.get("artifact_manifest_id") or generation.get("analysis_audio_manifest_id")
    if not manifest_id:
        await cms.transition_transcription_segment(unit_id, "failed", {
            "claim_token": claim_token,
            "failure_class": "missing_analysis_audio_manifest",
            "summary": "segment has no analysis-audio manifest",
        })
        return {"segment_id": unit_id, "state": "failed"}
    manifest = await cms.get_artifact_manifest(str(manifest_id), str(generation.get("tenant_id") or "default"))
    url = manifest.get("public_url")
    if not isinstance(url, str) or not url.strip():
        await cms.transition_transcription_segment(unit_id, "failed", {
            "claim_token": claim_token,
            "failure_class": "missing_analysis_audio_url",
            "summary": "analysis-audio manifest has no public URL",
        })
        return {"segment_id": unit_id, "state": "failed"}

    stop = asyncio.Event()
    heartbeat_failed = asyncio.Event()
    heartbeat_task = asyncio.create_task(
        _lease_heartbeat_loop(
            stop,
            heartbeat_failed,
            lambda: cms.heartbeat_transcription_segment(unit_id, claim_token, unit_fence),
            f"transcription-segment:{unit_id}",
        )
    )
    local_path: str | None = None
    try:
        start_ms = int(unit["start_ms"])
        end_ms = int(unit["end_ms"])
        fd, local_path = tempfile.mkstemp(suffix=".wav", prefix=f"transcript-segment-{unit_id}-", dir=ctx.get("temp_dir"))
        os.close(fd)
        await extract_audio_segment(
            url,
            local_path,
            start_ms,
            end_ms,
            timeout_sec=max(1800, int(ctx["settings"].TRANSCRIBE_TIMEOUT_SEC) * 2),
            trusted_cms_source=True,
        )
        service = TranscriptionService(
            ctx["model_manager"].stt,
            cms,
            temp_dir=ctx.get("temp_dir"),
            admission=ctx.get("workload_admission"),
        )
        response = await service.transcribe_file(
            local_path,
            language=str(generation.get("language") or ctx["settings"].STT_DEFAULT_LANGUAGE),
            word_timestamps=True,
        )
        segments = [segment.model_dump() for segment in response.segments]
        if heartbeat_failed.is_set():
            try:
                await cms.transition_transcription_segment(unit_id, "uncertain", {
                    "claim_token": claim_token,
                    "failure_class": "lease_heartbeat_failed",
                    "summary": "segment lease heartbeat failed before verification",
                })
            except Exception:
                logger.exception(
                    "transcription_segment_heartbeat_uncertainty_receipt_failed",
                    segment_id=unit_id,
                )
            return {"segment_id": unit_id, "state": "uncertain"}
        await cms.transition_transcription_segment(unit_id, "verified", {
            "claim_token": claim_token,
            "transcript_text": response.text,
            "transcript_segments": segments,
            "summary": "segment transcription verified",
            "artifact_manifest_ids": [str(manifest_id)],
        })
        try:
            await cms.finalize_transcription_generation(str(generation["id"]), _generation_content_stage(generation))
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code != 409 or "TRANSCRIPTION_INCOMPLETE" not in exc.response.text:
                raise
        return {"segment_id": unit_id, "state": "verified"}
    except Exception as exc:
        try:
            await cms.transition_transcription_segment(unit_id, "failed", {
                "claim_token": claim_token,
                "failure_class": provider_error_code(exc),
                "summary": str(exc)[-1000:],
            })
        except Exception:
            logger.exception("transcription_segment_failure_receipt_failed", segment_id=unit_id)
        raise
    finally:
        stop.set()
        await asyncio.gather(heartbeat_task, return_exceptions=True)
        if local_path and os.path.exists(local_path):
            try:
                os.unlink(local_path)
            except OSError:
                pass


def _generation_content_stage(generation: dict[str, Any]) -> dict[str, str] | None:
    proof = generation.get("terminal_proof")
    if not isinstance(proof, dict):
        return None
    value = proof.get("content_stage")
    if not isinstance(value, dict):
        return None
    required = ("request_id", "attempt_id", "claim_token", "fence_token", "input_fingerprint", "producer_event_id")
    if not all(isinstance(value.get(key), str) and value[key] for key in required):
        return None
    return {key: str(value[key]) for key in required}


async def artifact_coverage_task(
    ctx: dict[str, Any], claim: dict[str, Any]
) -> dict[str, str]:
    cms: CMSClient = ctx["cms_client"]
    request_id = claim["id"]
    token = claim["claim_token"]
    try:
        await cms.begin_artifact_coverage(request_id, token)
    except httpx.HTTPStatusError as exc:
        if exc.response.status_code in {404, 409}:
            logger.info("artifact_coverage_delivery_stale", request_id=request_id)
            return {"request_id": request_id, "state": "stale"}
        raise
    heartbeat_stop = asyncio.Event()
    heartbeat_failed = asyncio.Event()
    heartbeat_task = asyncio.create_task(
        _lease_heartbeat_loop(
            heartbeat_stop,
            heartbeat_failed,
            lambda: cms.heartbeat_artifact_coverage(request_id, token),
            f"artifact-coverage:{request_id}",
        )
    )
    correlation = {
        "request_id": request_id,
        "attempt_id": claim["attempt_id"],
        "claim_token": token,
        "fence_token": claim["fence_token"],
        "input_digest": claim["input_digest"],
        "producer_event_id": f"media:{claim['attempt_id']}",
    }
    content = claim["content"]
    artifact = claim["artifact"]
    model_manager: ModelManager = ctx["model_manager"]
    try:
        if artifact == "transcript":
            url = content.get("media_url") or content.get("original_url")
            if not url:
                raise RuntimeError("CMS transcript claim has no media URL")
            service = TranscriptionService(
                model_manager.stt,
                cms,
                temp_dir=ctx.get("temp_dir"),
                fetch_client=ctx.get("fetch_client"),
                admission=ctx.get("workload_admission"),
            )
            response = await service.transcribe_url(
                url,
                content_id=content["id"],
                word_timestamps=True,
                artifact_recovery=correlation,
            )
            if response.write_back_status != "ok":
                raise RuntimeError("transcript recovery was not persisted")
        elif artifact == "image_embedding":
            url = content.get("thumbnail_url") or content.get("media_url")
            if not url:
                raise RuntimeError("CMS image claim has no image URL")
            response = await _embed_via_api(
                ctx, url, content["id"], artifact_recovery=correlation
            )
            if response.get("write_back_status") != "ok":
                raise RuntimeError("image recovery was not persisted")
        else:
            raise RuntimeError("CMS returned an artifact outside Media capability")
        if heartbeat_failed.is_set():
            await cms.mark_artifact_coverage_uncertain(request_id, token)
            return {"request_id": request_id, "state": "uncertain"}
        await cms.accept_artifact_coverage(
            request_id, token, {"artifact": artifact, "write_back_status": "ok"}
        )
        return {"request_id": request_id, "state": "verifying"}
    except Exception:
        try:
            await cms.mark_artifact_coverage_uncertain(request_id, token)
        except Exception:
            # CMS lease recovery performs the same transition if the explicit
            # uncertainty receipt cannot be delivered during an outage.
            pass
        raise
    finally:
        heartbeat_stop.set()
        await asyncio.gather(heartbeat_task, return_exceptions=True)


def _build_redis_settings():
    """Parse REDIS_URL into arq's RedisSettings, applying ARQ_REDIS_DB."""
    return build_redis_settings(Settings())


class WorkerSettings:
    """arq picks this up via `arq src.worker.WorkerSettings`."""

    functions = [
        transcribe_task,
        func(artifact_coverage_task, max_tries=1),
        func(content_stage_transcript_task, max_tries=1),
        func(transcription_segment_task, max_tries=1),
    ]
    # Dispatchers are started by ``_startup`` instead of ARQ cron jobs.  ARQ
    # persists cron deliveries in the same queue as effects; with one long
    # STT job that design accumulated thousands of stale ticks and starved the
    # next cut.  The in-process loops are serialized, distributed-lock backed,
    # and stop cleanly with this worker.
    cron_jobs: list[Any] = []
    on_startup = _startup
    on_shutdown = _shutdown
    redis_settings = _build_redis_settings()
    # Keep one Media effect in flight.  This matches WorkloadAdmission's STT
    # limit and the Pods episode-family slot; a second ARQ task would only sit
    # behind the first while its fenced CMS claim ages toward expiry.
    max_jobs = _MAX_ARQ_JOBS
    # Keep finished job results around long enough for clients to poll.
    keep_result = 3600  # 1 hour
    # Refresh the health-check key every 30s (arq default is 3600s). The key's
    # TTL is interval+1s, so a dead worker's key expires within ~31s — this is
    # what makes the admin dashboard's "worker alive" signal timely instead of
    # up to an hour stale.
    health_check_interval = 30
    # Required for DELETE /v1/transcribe/jobs/{id} (batch cancel). Without this,
    # arq ignores Job.abort() and queued jobs run anyway.
    allow_abort_jobs = True
    # Long jobs need long timeouts; hosted providers still process long podcasts
    # asynchronously and can take several minutes end to end.
    job_timeout = 3600  # long-form segment extraction + STT
